version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: postgres_tls
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql
      - ./database_scripts:/docker-entrypoint-initdb.d
    ports:
     - "5432:5432"
